<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CW230111" failures="1" tests="7" name="FunctionalTests" time="26.457" errors="0" timestamp="2025-08-22T17:17:29 IST">
  <testcase classname="tests.LoginTest" name="testLogin" time="0.947"/>
  <testcase classname="tests.LoginTest" name="testLogin" time="0.375">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]
at tests.LoginTest.testLogin(LoginTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="tests.LoginTest" name="testLogin" time="0.671"/>
  <testcase classname="tests.LoginTest" name="testLogin" time="5.621"/>
  <testcase classname="tests.ProductsTest" name="testProductFilterLowToHigh" time="1.134"/>
  <testcase classname="tests.CartTest" name="testAddToCart" time="0.951"/>
  <testcase classname="tests.CheckoutTest" name="testCheckout" time="2.931"/>
</testsuite> <!-- FunctionalTests -->
